# Generated by Django 4.0.5 on 2022-06-03 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('note', models.TextField(default='', verbose_name='Задание')),
                ('status', models.IntegerField(choices=0, default=0, verbose_name='Статус')),
                ('importance', models.BooleanField(default=False, verbose_name='Важно')),
                ('public', models.BooleanField(default=False, verbose_name='Публично')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 13, 40, 9, 17781, tzinfo=utc), verbose_name='Выполнить до')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
