# Generated by Django 4.0.5 on 2022-06-03 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 14, 33, 40, 314403, tzinfo=utc), verbose_name='Выполнить до'),
        ),
    ]
