# Generated by Django 4.0.5 on 2022-06-03 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_model', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 15, 50, 56, 100589, tzinfo=utc), verbose_name='Выполнить до'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Отложено'), (1, 'Активно'), (2, 'Выполнено')], default=0, verbose_name='Статус'),
        ),
    ]
